import os
PathJoin = os.path.join

target = 'sched1'

Import('env')

mod = env.Clone()

module = mod.Module('load', target, etrace_sources = ['src/sched1.c'])

experiment_json = File('experiment.json')
sched1_stp = File('sched1.stp')

mod.Depends(module, [experiment_json, sched1_stp])

install_path = PathJoin(mod['INSTALL_VAR'], 'mbench', target)
mod.InstallTarget(install_path, experiment_json)
                 
installed_sched1_stp = mod.InstallTarget(install_path, sched1_stp)        
if env.SupportedPlatform('posix'):
    mod.AddPostAction(installed_sched1_stp, mod.Chmod(str(installed_sched1_stp), 0750))